### ISSUE TITLE
upgrade.php failed

### ISSUE THREAD

**Issue by amy1117** [digitalmethodsinitiative/dmi-tcat#295]
**Trying to upgrade databases by following the instructions.**

**I receive the following error:**

sudo php upgrade.php bigdata
2018-01-05 19:10:25     Running in interactive mode
2018-01-05 19:10:25     Restricting upgrade to bin bigdata
Would you like to execute this upgrade step: Fix time zone information in all meta tables (urls, mentions, hashtags) for tweets prior to 2016-11-12 20:10:02 ?? [y]es, [n]o or [a]ll for this operation? (time indication: expensive, commit )
y
2018-01-05 19:10:29     SQL query: update low_priority bigdata_urls X inner join bigdata_tweets T on X.tweet_id = T.id set X.created_at = T.created_at where X.created_at != T.created_at
2018-01-05 19:12:17     SQL query: update low_priority bigdata_mentions X inner join bigdata_tweets T on X.tweet_id = T.id set X.created_at = T.created_at where X.created_at != T.created_at
2018-01-05 19:13:59     SQL query: update low_priority bigdata_hashtags X inner join bigdata_tweets T on X.tweet_id = T.id set X.created_at = T.created_at where X.created_at != T.created_at
PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 144 Table './twittercapture/bigdata_hashtags' is marked as crashed and last (automatic?) repair failed' in /var/www/dmi-tcat/common/upgrade.php:1414
Stack trace:
#0 /var/www/dmi-tcat/common/upgrade.php(1414): PDOStatement->execute()
#1 /var/www/dmi-tcat/common/upgrade.php(1683): upgrades(false, true, 0, 'bigdata')
#2 {main}
  thrown in /var/www/dmi-tcat/common/upgrade.php on line 1414

**Also, my error log file shows the following lines:**

PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 144 Table './twittercapture/bigdata_hashtags' is marked as crashed and last (automatic?) repair failed' in /var/www/dmi-tcat/analysis/common/functions.php:927\nStack trace:\n#0 /var/www/dmi-tcat/analysis/common/functions.php(927): PDOStatement->execute()\n#1 /var/www/dmi-tcat/analysis/common/functions.php(18): get_all_datasets()\n#2 /var/www/dmi-tcat/analysis/index.php(5): require_once('/var/www/dmi-tc...')\n#3 {main}\n  thrown in /var/www/dmi-tcat/analysis/common/functions.php on line 927, 

**Finally, my analysis page displays:**

xxx.xxx.xxx.xxx is currently unable to handle this request.
HTTP ERROR 500

**Comment by amy1117** [comment]
I repaired the corrupted table. That resolved all the issues.
