### ISSUE TITLE
Server not responding when updating overview

### ISSUE THREAD

**Issue by fredrikjonasson** [digitalmethodsinitiative/dmi-tcat#361]
I have run into an issue when i am updating the overview on the localhost/analysis page. Even if i just try to work with a sample of 1 tweet i get the error. 

I have had the problem twice (just reinstalled the first time) and it seems to arise when i at the same time log in on the tcatserver from a serversoftware (DBeaver as an example). However, even after disconnecting, closing the program and even restarting the computer the problem remains.

Any clues on this?

**Comment by fredrikjonasson** [comment]
My apache error log: 
[Tue Apr 23 09:36:50.992660 2019] [mpm_prefork:notice] [pid 1053] AH00163: Apache/2.4.29 (Ubuntu) configured -- resuming normal operations
[Tue Apr 23 09:36:50.992723 2019] [core:notice] [pid 1053] AH00094: Command line: '/usr/sbin/apache2'
[Tue Apr 23 11:41:07.149886 2019] [php7:error] [pid 10273] [client 127.0.0.1:54504] PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000] [2002] No such file or directory in /var/www/dmi-tcat/common/functions.php:6\nStack trace:\n#0 /var/www/dmi-tcat/common/functions.php(6): PDO->__construct('mysql:host=loca...', 'tcatdbuser', 'DnPz6EsSu3KFgXZ...', Array)\n#1 /var/www/dmi-tcat/analysis/common/functions.php(9): pdo_connect()\n#2 /var/www/dmi-tcat/analysis/ajax.serverload.php(3): require_once('/var/www/dmi-tc...')\n#3 {main}\n  thrown in /var/www/dmi-tcat/common/functions.php on line 6, referer: http://localhost/analysis/
[Tue Apr 23 11:41:10.144083 2019] [php7:error] [pid 3057] [client 127.0.0.1:54956] PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000] [2002] No such file or directory in /var/www/dmi-tcat/common/functions.php:6\nStack trace:\n#0 /var/www/dmi-tcat/common/functions.php(6): PDO->__construct('mysql:host=loca...', 'tcatdbuser', 'DnPz6EsSu3KFgXZ...', Array)\n#1 /var/www/dmi-tcat/analysis/common/functions.php(9): pdo_connect()\n#2 /var/www/dmi-tcat/analysis/ajax.serverload.php(3): require_once('/var/www/dmi-tc...')\n#3 {main}\n  thrown in /var/www/dmi-tcat/common/functions.php on line 6, referer: http://localhost/analysis/
[Tue Apr 23 11:46:28.039207 2019] [mpm_prefork:notice] [pid 1053] AH00169: caught SIGTERM, shutting down
[Tue Apr 23 11:46:50.449821 2019] [mpm_prefork:notice] [pid 984] AH00163: Apache/2.4.29 (Ubuntu) configured -- resuming normal operations
[Tue Apr 23 11:46:50.460027 2019] [core:notice] [pid 984] AH00094: Command line: '/usr/sbin/apache2'

**Comment by fredrikjonasson** [comment]
[SOLVED]
Flushed the DNS-cache. Checked ifconfig (ubuntu) and then updated base_url accordingly in config.php.
